Add field attribute 'widget' to field Dict from zope.schema
plone/plone.schema pull request #13
Opened 2021-07-02 11:58 UTC by ksuess

As the Dict field is a mighty field that can be used for many diverse dictionaries and diverse use cases, we need the widget info to let Volto know which Widget to apply.

2021-07-02 11:58 UTC, mister-roboto commented
@ksuess thanks for creating this Pull Request and help improve Plone!

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass.

Whenever you feel that the pull request is ready to be tested, either start all jenkins jobs pull requests by yourself, or simply add a comment in this pull request stating:

```
@jenkins-plone-org please run jobs
```

With this simple comment all the jobs will be started automatically.

Happy hacking!

2021-07-02 12:56 UTC, ksuess commented
@jenkins-plone-org please run jobs

2021-07-02 20:39 UTC, sneridagh approved these changes

2021-07-05 11:24 UTC, ksuess commented
@jenkins-plone-org please run jobs

2021-07-05 11:31 UTC, ksuess commented
I would like to separate the changes on this field Dict and other fields.
If this PR is OK, it can be a blueprint for all other fields. But that later PR should be reviewed carefully as this means to enrich zope.schema fields in plone.schema: how to communicate this? It will cause a lot of wasted developer time if it is not absolutly clear that the Dict field from **plone.schema** is needed to get this widget attribute.

2021-07-05 12:21 UTC, ksuess commented
@jenkins-plone-org please run jobs

2021-07-05 15:23 UTC, ksuess commented
@jenkins-plone-org please run jobs

2021-07-05 17:00 UTC, ksuess commented
@jenkins-plone-org please run jobs

2021-07-06 10:43 UTC, jensens requested changes
OK, I think I understand the intend of the PR, but I am not happy with it. I do not think it is a good idea to subclass all `zope.schema` to get a widget attribute into `__init__`. So, then we have to use them everywhere as well, right? Probably we should discuss this before merging this, to find a solution with less impact. And - if I get it right - it might be better fot this series of changes to discuss it in a PLIP.

2021-07-06 20:02 UTC, jensens commented
I had a call with @ksuess and together we found a way better solution to solve the problem: directives adding tagged values to the schema. This way the same mechanism will be used as we already use for z3cform. This is simple, well documented and we do not need to create a heap of subclasses.

2021-07-07 09:48 UTC, sneridagh commented
@jensens That is great and sounds good! So, the idea is to use plone.autoform hints? 

I think this is very important since we need more expressiveness in current serialization of the JSON schemas.

So you both will champion this? (Just sayin' ;) )

2021-07-07 09:55 UTC, sneridagh commented
I only have an issue with using plone.autoform... it was thought and implemented around z3c.form ... and it depends on it, which could be an issue in the future.

Wondering if we could implement an agnostic hint-based using tagged values framework for this use case.

/cc @tisto

2021-07-07 11:58 UTC, jensens commented
This hints are in fact a zope.interface feature, tagges values on an interface class. plone.autoform just utilizes this feature. And its the official/recommended way to add information to interface classes.

2021-07-07 13:50 UTC, sneridagh commented
@jensens Cool! Just stumbled upon languageindependent fields in PAM: 

https://github.com/plone/plone.app.multilingual/blob/master/src/plone/app/multilingual/dx/directives.py

I'd say it's what we need :) now, we need to decide where to place it :)

2021-07-07 14:16 UTC, jensens commented
I think `plone.autoform` is ok. We just enhance its domain to support Volto automatic form info too. 

Also I think we can read what is configured for z3cform and transform this to a suitable configuration for Volto form in cases where we have no specific schema tagged values for Volto. Like if a datetimewidget for z3c.form is configured to not show the time input the information can be transformed to a Volto widget (i.e. `vwidget` directive) configuration dict. Thus the transformation to Volto is less work. We could log a debug message if this happens.

2021-07-08 07:59 UTC, jensens commented
I propose to:

1) close this PR
2) schedule a meeting (i.e. using the Plone Discord Volto Voice channel).
3) write a PLIP for Plone describing what we want to achieve. Split PLIP up in section with low-hanging fruits (directives) and the next steps (like auto-trasformation of widget information to Volto-Style).
4) implement it :)

2021-07-09 13:09 UTC, ksuess commented
I agree to close this PR focussed on the single DictField.

And if I am not completly wrong, there is indeed no need to introduce a new directive or any other implementation to provide some widget info for the frontend.
The widget directive allows widget options. https://github.com/plone/plone.autoform/blob/2ca75e23e47a0c220bafb5501a2a918551c777ee/plone/autoform/directives.py#L91
These widget options are provided by the types endpoint: https://github.com/plone/plone.restapi/blob/744a00126fd96f7818901820c4bd37158941edc7/src/plone/restapi/types/adapters.py#L82


So they are available for the frontend to decide which widget to apply and even which version, according to further optional attributes / options of the existing widget directive.

2021-07-09 13:51 UTC, sneridagh commented
I thought that you should pass a class unconditionally ( * The second positional arg is a widget class, again specified as either a direct reference or a dotted path.) Does it work without assigning anything?

```
    Option 2:
      ``widget('field1', TextWidget, label=u'My label')``
      This option makes it possible to configure a custom widget _and_
      customize its attributes.
      * The first positional arg is a string giving the name of a single field.
      * The second positional arg is a widget class, again specified as either
        a direct reference or a dotted path.
      * The remaining args are keyword arguments mapping arbitrary names to
        arbitrary values. These will be set as attributes of the widget when it
        is constructed.
```
This would be a nice workaround although the Widget assigner still needs to support it. 

However, I would like it to be more explicit than a workaround, hidden under "widgetOptions" dict. 

Something like: 

```
directives.volto_widget(vocabularytermstranslation_field="foo")
```

What do you think?

2021-07-09 14:23 UTC, jensens commented
I think explicit is better. it can be like `directives.volto_widget(vocabularytermstranslation_field="foo")` in a simple case and `directives.volto_widget(vocabularytermstranslation_field="foo", param1=value1, param2=value2)` and so on for widgets with need of more parameters.

2021-07-10 07:50 UTC, ksuess commented
Before we decide to introduce a new directive for volto widget:
https://github.com/plone/plone.restapi/pull/1172

2021-07-11 09:09 UTC, jensens commented
Since this is an PR I close it now. Lets follow up on @ksuess good idea in plone/plone.restapi#1172.

2021-07-11 09:09 UTC, closed without merging